class ItemData {
  List listA = [
    'Option A',
    'Option A',
    'Option A',
    'Option A',
    'Option A',
    'Option A',
    'Option A',
    'Option A',
    'Option A'
  ];

  List listB = [
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
    'B Mode',
  ];

  List listC = [
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
    'C selected',
  ];

  List listD = [
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
    'Mode D',
  ];
}
